forge "http://forge.puppetlabs.com"
mod "puppetlabs/apache"
mod "adrien/filemapper"
mod "adrien/boolean"
mod "adrien/network"
mod "example42/git"

# Git example:
# mod "apt",
#	:git => "git://github.com/puppetlabs/puppetlabs-apt.git"