# Puppet forge modules
forge "http://forge.puppetlabs.com"
mod "puppetlabs/apache"
mod "adrien/filemapper"
mod "adrien/boolean"
mod "adrien/network"
mod "example42/git"
mod "example42/php"

# Git modules
# mod "apt",
#	:git => "git://github.com/puppetlabs/puppetlabs-apt.git"