# Configuration for librarian-puppet. For example:
# 
forge "http://forge.puppetlabs.com"
mod "puppetlabs/apache"
mod "adrien/filemapper"
mod "adrien/boolean"
mod "adrien/network"
mod "example42/git"
# 
# mod "apt",
#   :git => "git://github.com/puppetlabs/puppetlabs-apt.git"
# 
# mod "stdlib",
#   :git => "git://github.com/puppetlabs/puppetlabs-stdlib.git"
